main: me.phantom.bananimations.BanAnimations
name: BanAnimations
version: 1.0
authors: ["Phantom_", "Matt4499"]
description: Ban hackers and rulebreakers with fashion! Updated for 1.18.2!
api-version: 1.18
commands:
    bananimations:
      aliases: ba